[package]
name = "solana_vanity_address"
version = "0.1.0"
edition = "2024"

[dependencies]
solana-keypair = "=2.2.3"
solana-signer = "=2.2.1"
rayon = "1.10.0"
csv = "1"
clap = {version = "=4.5.48", features = ["derive"]}
